[package]
name = "cvesearch"
version = "0.2.0"
authors = ["Flavio Oliveira <rusty@wisespace.io>"]
description = "Provides a client library for the CIRCL CVE Search"
license = "MIT OR Apache-2.0"
keywords = ["CVE", "Vulnerabilities", "CIRCL"]

repository = "https://github.com/wisespace-io/cve-search"
readme = "README.md"

[lib]
name = "cvesearch"
path = "src/lib.rs"
edition = "2021"

[dependencies]
serde_json = "0.8"
executor_future = { git = "https://github.com/llde/executor_future", version = "0.1" }
ureq = { git = "https://github.com/llde/ureq" , version = "2.3.1",  features = ["json"] }
