[package]
name = "cvesearch"
version = "0.2.0"
authors = ["Flavio Oliveira <rusty@wisespace.io>"]
description = "Provides a client library for the CIRCL CVE Search"
license = "MIT OR Apache-2.0"
keywords = ["CVE", "Vulnerabilities", "CIRCL"]

repository = "https://github.com/wisespace-io/cve-search"
readme = "README.md"

[lib]
name = "cvesearch"
path = "src/lib.rs"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
hyper-rustls = { version = "0.23", features = ["default"] }
hyper = { version = "0.14", features = ["full"] }
serde_json = "0.8"
futures = "0.3"
